# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run the tests
        run: npm test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.WEBSITESECRET }}

      - name: Build
        run: npm run build
        
      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
              server: ${{ secrets.PORTFOLIO_SITE_SERVER}}
              username: ${{ secrets.PORTFOLIO_SITE_USER}}
              password: ${{ secrets.PORTFOLIO_SITE_PASS}}

